### ISSUE TITLE
Vendor Question

### ISSUE THREAD

**Issue by mwhittaker** [cw75/high-performance-lattices#1]
Why are some external dependencies like [Google Test](https://github.com/cw75/high-performance-lattices/tree/master/vendor/gtest) and [Google Benchmark](https://github.com/cw75/high-performance-lattices/tree/master/vendor/gbenchmark) put in the [vendor directory](https://github.com/cw75/high-performance-lattices/tree/master/vendor) but others like zeromq and Protocol Buffers aren't?

**Comment by cw75** [comment]
Only gtest and gbench are required to test and benchmark the core lattice library. zmq and protobuf are used specifically for the kvs stuff. I should have added them all but I haven't had a chance to...

**Comment by mwhittaker** [comment]
Ah, got it. I'm not very familiar with C++ project layout and dependency management and all that, so I wasn't sure if there was some idiom for deciding what goes in a vendor directory and what doesn't.

**Comment by jhellerstein** [comment]
I do believe its best to put all external deps in vendor.
